### ISSUE TITLE
Use `redis.createClient` rather than the RedisClient constructor

### ISSUE THREAD

**Issue by thebigredgeek** [davidyaha/graphql-redis-subscriptions#10]
It's a bit confusing that we are using the RedisClient constructor directly, as all of the docs (including options) for node_redis are around `redis.createClient`.  Because of this, there is at least one discrepancy with passing connection options to redis.  According to current [node_redis docs here](https://github.com/NodeRedis/node_redis/blame/master/README.md#L184), the client should be able to specify a `url` option rather than passing `host` and `port` options through the connection hash that you pass through to `node_redis`.  However, the `RedisClient` constructor does not support a `url` property.  The `url` property is normalized and split into `host` and `port` properties through a call [here](https://github.com/NodeRedis/node_redis/blob/master/index.js#L1081), which dives into `lib/createClient.js` and parsed into `host` and `port` [here](https://github.com/NodeRedis/node_redis/blob/master/lib/createClient.js#L26).  Passing the `url` option through `options.connection` in `RedisPubSub` constructor causes an attempted connection to `redis://127.0.0.1:6379`, regardless of what is passed via `url`.  Because of this discrepancy, and for the sake of developer sanity, I think it makes more sense to interact with the publicly documented API of `node_redis` (aka, `redis.createClient(options: Object)` rather than interface with the `RedisClient` constructor directly as it fits more inline with the `node_redis` docs and this lib provides a passthrough via `options.connection` which will be assumed to follow the `node_redis` publicly doc'd API.  I am willing to put in a PR to make this switch later this week.

**Comment by davidyaha** [comment]
@thebigredgeek Cool! I wasn't aware of that actually. Would definitely merge a PR that changes the API from the constructor to the createClient method.

Thanks for the insight!

**Comment by thebigredgeek** [comment]
Cool!  Will submit later this week.  Thanks @davidyaha

**Comment by youngboy** [comment]
hi @thebigredgeek , any update on this issue ?

**Comment by davidyaha** [comment]
@youngboy Actually working on it right now.. will be published in a couple of hours

**Comment by davidyaha** [comment]
@youngboy Just published 1.1.4

**Comment by thebigredgeek** [comment]
Whoops sorry guys haha.  Completely forgot about this :(

**Comment by davidyaha** [comment]
NP @thebigredgeek  :)

**Comment by mschipperheyn** [comment]
@thebigredgeek Ah darn. `ioredis` is still hard coded.
