### ISSUE TITLE
Example project

### ISSUE THREAD

**Issue by perrosnk** [davidyaha/graphql-redis-subscriptions#103]
Could someone provide some code using `graphql-redis-subscriptions`?
I am facing some difficulties getting the data sent to the client although the subscription is called on the server.

**Comment by igorlesnenko** [comment]
@perrosnk

Wrapper
https://github.com/spikenail/spikenail-pubsub-redis/blob/master/src/PubSub.ts

Creating a server
https://github.com/spikenail/spikenail/blob/884fdd615ea7f7747d2261da4be662d39509933f/src/lib/Spikenail.js#L130

Usage
https://github.com/spikenail/spikenail/blob/884fdd615ea7f7747d2261da4be662d39509933f/src/lib/MongoDBModel.js#L1472

**Comment by perrosnk** [comment]
@igorlesnenko thanks!
