### ISSUE TITLE
Documentation - redis pubsub

### ISSUE THREAD

**Issue by serendipity1004** [davidyaha/graphql-redis-subscriptions#125]
I am curious because I am getting a `subscriptionsClient.subscribe is not a function` error and I do not understand the source of it.

The code below in documentation,

```
import { RedisPubSub } from 'graphql-redis-subscriptions';

const pubsub = new RedisPubSub({
  connection: {
    host: REDIS_DOMAIN_NAME,
    port: PORT_NUMBER,
    retry_strategy: options => {
      // reconnect after
      return Math.max(options.attempt * 100, 3000);
    }
  }
});
```

It means replace the pubsub instance below with the pubsub instance created from new RedisPubSub right?

```
const SOMETHING_CHANGED_TOPIC = 'something_changed';

export const resolvers = {
  Subscription: {
    somethingChanged: {
      subscribe: () => pubsub.asyncIterator(SOMETHING_CHANGED_TOPIC),
    },
  },
}
```

**Comment by davidyaha** [comment]
Hey @serendipity1004! Yes it does mean that. where are you getting this error? 
Thanks using this package!

**Comment by serendipity1004** [comment]
@davidyaha  Hi, I have managed to resolve the error but I have another question.

Even if I use a different package than ioredis to publish redis event, I can still subscribe to the same channel as long as the channel names are identical in another subscription server that uses ioredis right?

**Comment by davidyaha** [comment]
Yes the channels are handled by redis and the channel names are not augmented in any way when passed to a redis server or cluster so you can safely subscribe to a channel from graphql-subscriptions or any other entities in your network

**Comment by serendipity1004** [comment]
@davidyaha  Thank you very much!
