### ISSUE TITLE
Upgrade to graphql-subscriptions v1.0

### ISSUE THREAD

**Issue by 19majkel94** [davidyaha/graphql-redis-subscriptions#127]
Hi @davidyaha! 😉 

Apollo team has recently published v1.0 release of graphql-subscriptions. They've changed the return type of the method from `boolean` to `Promise<void>`:
https://github.com/apollographql/graphql-subscriptions/blob/master/CHANGELOG.md#100

Can you upgrade `graphql-redis-subscriptions` too? Or maybe I could send the PR with this changes? 

Thanks!

**Comment by davidyaha** [comment]
Would gladly merge a PR from you! Otherwise I'll be able to upgrade during the next couple of weeks.
Thanks for the heads up!

**Comment by 19majkel94** [comment]
Great! Can we also make `graphql-subscriptions` a peer dependency on the occasion of this major release? It would be easier for library consumers than forcing them to dedupe the deps tree.

**Comment by davidyaha** [comment]
Good idea, go for it!

**Comment by 19majkel94** [comment]
@davidyaha
Thanks! Works like a charm! 🎉
