### ISSUE TITLE
Property 'publish' in type 'RedisPubSub' is not assignable to the same property in base type 'PubSubEngine'.

### ISSUE THREAD

**Issue by itmayziii** [davidyaha/graphql-redis-subscriptions#134]
Using this dependency gives me a build error even though things appear to be working fine. Seems the class RedisPubSub does not implement PubSubEngine correctly. 

![screen shot 2019-01-14 at 4 37 01 pm](https://user-images.githubusercontent.com/13625506/51142726-b7993c00-181a-11e9-88f9-6f4239fe54b9.png)

Currently using version  "graphql-redis-subscriptions": "~2.0.0"

**Comment by TranHung92** [comment]
I had the same issue. `yarn add graphql-subscription` solved the problem for me.

**Comment by davidyaha** [comment]
Hey @itmayziii!
Sorry for the late reply.
`graphql-subscriptions` updated their publish signature at v1.
Make sure that your graphql-subscriptions version is 1.0.0 or above and please let me know if that helped.
