### ISSUE TITLE
Issue with importing ioredis

### ISSUE THREAD

**Issue by StupidSexyJake** [davidyaha/graphql-redis-subscriptions#145]
The example code used in section Creating the Redis Client of the readme has the following import:

`import * as Redis from 'ioredis';`

This results in an error message: 

```
publisher: new Redis(options),
           ^

TypeError: Redis is not a constructor
```

To fix this, you simply need to change the import to:

`import Redis from 'ioredis';`

**Comment by davidyaha** [comment]
Hey @StupidSexyJake,
Thanks for reporting this issue.
I think it is dependent of what module system you use. 
AFAIK the docs was written using `commonjs` and `typescript` and this is why it worked for them.
It might also be a case of different version of `ioredis`...

Could you specify your versions, language and module system?

Thanks!

**Comment by StupidSexyJake** [comment]
I'm using ES6. Here's my package.json:

```
{
  "name": "server",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "engines": {
    "node": "10.11.0"
  },
  "scripts": {
    "start": "nodemon --exec babel-node src/index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.1.6",
    "@babel/node": "^7.0.0",
    "@babel/preset-env": "^7.1.6",
    "@babel/register": "^7.0.0",
    "axios": "^0.18.0",
    "chai": "^4.2.0",
    "mocha": "^5.2.0",
    "nodemon": "^1.18.7",
    "morgan": "^1.9.1"
  },
  "dependencies": {
    "apollo-server": "^2.2.3",
    "apollo-server-express": "^2.2.3",
    "bcrypt": "^3.0.2",
    "cors": "^2.8.5",
    "dataloader": "^1.4.0",
    "dotenv": "^6.1.0",
    "express": "^4.16.4",
    "graphql": "^14.0.2",
    "graphql-iso-date": "^3.6.1",
    "graphql-redis-subscriptions": "^2.1.0",
    "graphql-resolvers": "^0.2.2",
    "ioredis": "^4.6.2",
    "jsonwebtoken": "^8.4.0",
    "pg": "^7.6.1",
    "sequelize": "^4.41.2",
    "uuid": "^3.3.2"
  }
}
```

**Comment by davidyaha** [comment]
Yeah so it's probably my first assumption. TS transpiled default imports differently than babel..
There is a good article on the reasons here: https://itnext.io/great-import-schism-typescript-confusion-around-imports-explained-d512fc6769c2

Regardless, it should be noted that the code examples are written in TS.
Closing the issue, but thanks for mentioning that for future reference 👍

**Comment by EhsanSarshar** [comment]
try to import it like this
`const Redis = require('ioredis')`
**commonjs** like

**Comment by thiendang** [comment]
> try to import it like this `const Redis = require('ioredis')` **commonjs** like

Thanks [TheEhsanSarshar](https://github.com/TheEhsanSarshar) . It's work well for me!!

**Comment by MoElaSec** [comment]
```js
const IORedis = require("ioredis");

const redis = new IORedis.Redis({
  host: process.env.REDIS_HOST || "127.0.0.1",
  port: Number(process.env.REDIS_PORT) || 6379,
  password: process.env.REDIS_PASSWORD || undefined,
  db: Number(process.env.REDIS_DB) || 0, // Default Redis DB
});
```

you will need this for CommonJS
