### ISSUE TITLE
Is there any way to define some PREFIX or SCOPE ?

### ISSUE THREAD

**Issue by workforcecity** [davidyaha/graphql-redis-subscriptions#160]
I'm working on a react application which depends highly on real time data.
Using redis pubsub and it works fine.

My problem is I have multiple deployments of this application
1 - abc.somedomain.com 
2 - xyz.somedomain.com

I want to share 1 redis cluster between these 2 deployments. Now the issue is, if some data is published on some channel "channelABC" from 1st deployment, it visible for 2nd deployment as well. 

Is there any way to use some kind of prefix or scope just like
https://github.com/louischatriot/node-redis-pubsub

**Comment by davidyaha** [comment]
Hey @workforcecity thanks for reaching out.
There are multiple options to filter events or subscribing to redis channels and there are a couple of examples in the README file. But choosing the right one for you is dependant on the solution you are aiming at. It's a bit unclear from your description, what is the current system architecture?
Multiple deployments of the same app meaning multiple graphql servers? or just multiple subdomains that are subscribing from the same graphql endpoint?

Let me know and I'll point you in the right direction.

**Comment by kiyasov** [comment]
> I'm working on a react application which depends highly on real time data.
> Using redis pubsub and it works fine.
> 
> My problem is I have multiple deployments of this application
> 1 - abc.somedomain.com
> 2 - xyz.somedomain.com
> 
> I want to share 1 redis cluster between these 2 deployments. Now the issue is, if some data is published on some channel "channelABC" from 1st deployment, it visible for 2nd deployment as well.
> 
> Is there any way to use some kind of prefix or scope just like
> https://github.com/louischatriot/node-redis-pubsub

Have you found a solution?
