### ISSUE TITLE
Using pattern in subscription and knowing destination topic

### ISSUE THREAD

**Issue by tomasAlabes** [davidyaha/graphql-redis-subscriptions#166]
Hi, first thank you for your work in this project!

I was trying to use it subscribing to a redis topic using a pattern and doesn't seem to be working:

```typescript
mySubscription: {
  subscribe: (_, args) => pubsub.asyncIterator(`project.${args.id}.*`),
  resolve: (payload: any, args, context, info) => {
    // I received this message from which topic? Question even using [topics] in asyncIterator
    return payload;
  }
}
```
* Can I use a patter in the asyncIterator?
* Can I get the topic in the resolver? I can add the topic into the payload but I was wondering if there's another cleaner approach.

Thanks!

**Comment by davidyaha** [comment]
Hey @tomasAlabes!
Thanks for your interest and sorry for the lack of examples but for your first question, I think this will work:
```
mySubscription: {
  subscribe: (_, args) => pubsub.asyncIterator(`project.${args.id}.*`, { pattern: true }),
  resolve: (payload: any, args, context, info) => {
    return payload;
  }
}
```
If that ends up working, would you consider adding that example to the README?

Regarding your second question, I'm afraid there's no elegant way of doing that without changing the way `graphql-js` calls the subscriptions resolver. That basically means opening a PR for that.

What is your use case? I wonder if that will be a common enough case to make that change.

**Comment by tomasAlabes** [comment]
Hi @davidyaha, thanks for your response! Indeed your `pattern` option worked :) I will create a PR to add it to the readme. Any other option that people should know?

On the 2nd point, in my subscription I send a union of types to the client, so depending on the topic from which I get the message, is the graphql type I'm sending to the client. At the moment I'm sending some metadata in the event itself and from that I create the right gql type. Maybe it's useful to add the topic in the context? Idk. But at least that's my use case.

**Comment by davidyaha** [comment]
Glad to hear it worked 🎉 
A PR with an example would be great!

As far I understand it should be a PR to `graphql-js` so we should define the use case a bit. Basically what we need is a way to push to the `AsyncIterable` metadata to be added to something like info variable.

Maybe open a RFC issue on https://github.com/graphql/graphql-js and get some feedback on the idea?

**Comment by tomasAlabes** [comment]
Created the PR with the example. Thanks for the tip.
I will analyze if the RFC is strong enough and maybe ask there what they think.

Keep up the good work :)

**Comment by davidyaha** [comment]
Thanks @tomasAlabes!
