### ISSUE TITLE
Using non-local Redis server prevents proper registration of subscriptions

### ISSUE THREAD

**Issue by servernoj** [davidyaha/graphql-redis-subscriptions#184]
I am using this library with 2 instances of `ioredis` supplied to the `RedisPubSub` constructor as suggested in the docs (with minor modifications), for instance 
``` js
const options = {
  host: REDIS_DOMAIN_NAME,
  port: PORT_NUMBER
}

const pubsub = new RedisPubSub({
  publisher: new Redis(options),
  subscriber: new Redis(options)
})
```
I run application code (GraphQL server with `RedisPubSub` based subscriptions) in 2 environments `dev`/`prod` while having different settings for `REDIS_DOMAIN_NAME` and `PORT_NUMBER` in each environment.

The `dev` environment (based  on local node process) works with Redis server running off of **docker container** and is available at `localhost:6379`. The `prod` environment is hosted in AWS Fargate cluster (single task so far) and uses Redis server running off of container on EC2 instance (to be later moved onto AWS hosted ElasticCache Redis cluster). 

Redis **monitor** is instantiated within server code (separate `ioredis` instance) to observe realtime responses of the connected Redis server. All monitor messages are printed onto console. 

In both cases (`dev` and `prod` environments) I use the same **GraphQL client** (console version) that subscribes to the same set of topics. The client is configured to respect selected environment, so it "knows" correct URL of the GraphQL server. 

While in `dev` environment, i.e. with Redis server at `localhost:6379`, everything works OK. Redis monitor observes subscription activity. GraphQL subscriptions work as expected. 

While in `prod` environment, i.e. using **external** Redis server, request for subscription from the client is seen (via console logs) to arrive to subscription resolver, i.e the following definition of the subscription resolver
``` js
{
   subscribe: () => {
      logger.info('+++++++++++++++++++++++++')
      return pubsub.asyncIterator(labels)
   }
}
```
prints `+++...+++` (when client knocks in with subscription request) but does not result in _subscribing to topics_ to appear on Redis monitor (`labels` is an array of subscription topics).

The client does respond to publishing of subscribed topics, but instead reports `MaxRetriesPerRequestError` error with the following message:

> Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.

The Redis server **is accessible** from within the app as it can correctly monitor set/get operations issued from `redis-cli`

According to the documentation:

> Calling the method `asyncIterator` of the RedisPubSub instance will send redis a SUBSCRIBE message to the topic provided and will return an AsyncIterator binded to the RedisPubSub instance and listens to any event published on that topic.

This is not happening when Redis server is not local. At least the fact of "RedisPubSub instance will send redis a SUBSCRIBE message" is not reflected on the monitor. 

<hr/>

It is my understanding that call to `asyncIterator` does not result in actual subscribing when `RedisPubSub` instance is fed with `ioredis` instances pointing to external Redis server.

**Comment by servernoj** [comment]
The problem happens when you go 'smart' and instead of plane `new Redis(options)` (in RedisPubSub constractor) use something like `new Redis(options)...connect()` to insure that `ioredis` instance gets connected to Redis server prior using it. I overcomplicated the design and had a `Promise` supplied to `RedisPubSub` constructor instead of the plain `ioredis` instance. This in turn resulted `RedisPubSub`  being instantiated with _default options_ which assumed using `localhost:6379` pointing to nowhere on `prod` environment...so the reason for timeouts. My other `ioredis` instance was something separate so it worked fine proving me nothing but the fact that Redis server is up and running.

I hope this issue may help someone to avoid my same mistake.

**Comment by PandasProperty** [comment]
@servernoj thank you very much
