### ISSUE TITLE
[Feature] Please provide an option to use custom serializers (not just reviver) to handle circular references

### ISSUE THREAD

**Issue by vnenkpet** [davidyaha/graphql-redis-subscriptions#185]
For my app, I'd need to pass a TypeOrm Entity that can often have circular reference and I want this to work out of box. It actually does with the default graphql-subscriptions PubSub implementation, but since this one uses JSON.Stringify instead of letting me choose this breaks my app when replaced. I'd need to use something like [flatted](https://www.npmjs.com/package/flatted) which stringify and parse methods require to never be combined with JSON.Parse and JSON.Stringify, which seems to be impossible while using this package.  

I don't think anything that has been said in https://github.com/davidyaha/graphql-redis-subscriptions/issues/101 solves my problem.

**Comment by davidyaha** [comment]
Hey @vnenkpet,

Sorry for my late response, as I was on vacation this past month.
I would happily merge a PR allowing this option but you might want to consider overriding your TypeOrm base class [toJSON](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON_behavior) method.

Let me know if that works for you.
