### ISSUE TITLE
It always tries to connect 127.0.0.1

### ISSUE THREAD

**Issue by nouman91** [davidyaha/graphql-redis-subscriptions#194]
I have been facing this weird problem for past couple of days. No matter what host url I specify it always tries to connect '127.0.0.1'. I have tried using node_redis the same error no help. If I connect to redis independently outside of 'graphql-redis-subscriptions' it works. Here is my code:

```js
/**
 * Redis options
 */
const options = {
  host: process.env.REDIS_HOST || '127.0.0.1',
  port: process.env.REDIS_HOST_PORT || 6379,
  retryStrategy: times => {
    // reconnect after
    return Math.min(times * 50, 2000);
  }
};

const pubsub = new RedisPubSub({
    publisher: new Redis(options),
    subsciber: new Redis(options),
})

```

Please help

**Comment by davidyaha** [comment]
Hey @nouman91! 

What versions of ioredis or node_redis do you use?
Have you tried using the `connection` option to pass in the options object? https://github.com/davidyaha/graphql-redis-subscriptions/blob/master/src/redis-pubsub.ts#L6

**Comment by nouman91** [comment]
Hey @davidyaha 

Thank you for replying quickly. Your suggestion helped me and it is now fixed, thank you so much.

But please update readme file I have spent almost two days on it, and I have tried God knows so many things to make it work :(. Here is my sample code which is working. 

```js
const { RedisPubSub } = require("graphql-redis-subscriptions");
const Redis = require("ioredis");

/**
 * Redis options
 */
const options = {
  host: process.env.REDIS_HOST || "127.0.0.1",
  port: process.env.REDIS_HOST_PORT || 6379,
  retryStrategy: times => {
    // reconnect after
    return Math.min(times * 50, 2000);
  }
};

const pubsub = new RedisPubSub({
  connection: options,
  publisher: Redis,
  subsciber: Redis
});

You can close this issue
```

**Comment by davidyaha** [comment]
Hey @nouman91,
I am happy to hear that your problem was fixed but looking at the code snippet that you've added here, I am actually quite confused about the reason why this had worked for you.

As you can see here: https://github.com/davidyaha/graphql-redis-subscriptions/blob/master/src/redis-pubsub.ts#L28-L51

The connection initialization part of the constructor expects either the `connection` or the `publisher` and `subscriber`. In the code you've added above, you are using both options. 

Would you mind creating a sample repo so I could further look into it?
If you can't spare the time to do so, please specify the versions of the packages you are using.
- ioredis
- graphql-redis-subscriptions

After I'll figure out what happened here, I could safely update the readme with instructions that are more clear about connection initialization.

Thanks ahead.

**Comment by nouman91** [comment]
Ok, should I change my code to have only the connection object? Please clarify.

I would love to create a repo to help you but my project is near to completion it will take me couple of weeks to get back to you with a repo.

The versions I am using:

- graphql-redis-subscriptions:2.1.1
- ioredis: 4.14.1

**Comment by kierangilliam** [comment]
I'm running into a similar issue. When I pass the config straight into Redis, like in the example:

```
import { RedisPubSub } from 'graphql-redis-subscriptions';
import * as Redis from 'ioredis';

const options = {
  host: REDIS_DOMAIN_NAME,
  port: PORT_NUMBER,
  retryStrategy: times => {
    // reconnect after
    return Math.min(times * 50, 2000);
  }
};

const pubsub = new RedisPubSub({
  ...,
  publisher: new Redis(options),
  subscriber: new Redis(options)
});
```

The client only attempts to connect locally.

When I do

```
import { RedisPubSub } from 'graphql-redis-subscriptions'
import * as Redis from 'ioredis'

// Manually set for testing
process.env.REDIS_PASSWORD='XXX' 
process.env.REDIS_PORT='25061' 
process.env.REDIS_HOST='redis-XXXX.ondigitalocean.com'

const host = process.env.REDIS_HOST || 'localhost'
const port = process.env.REDIS_PORT || '6379'

console.log(`Attempting to connect to redis ${host}:${port}`)

const options = {
    host,
    port,
    password: process.env.REDIS_PASSWORD,
    // reconnect after
    retryStrategy: times => {
        return Math.min(times * 50, 2000);
    }
}

const pubsub = new RedisPubSub({
    connection: options,
    subscriber: Redis,
})


export default pubsub 
```

I get `axRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.`. I tested connecting using the cli with the same credentials and had no issues.
