### ISSUE TITLE
Improvement: Redis connection die causing node crash

### ISSUE THREAD

**Issue by youngboy** [davidyaha/graphql-redis-subscriptions#22]
according to https://github.com/NodeRedis/node_redis/issues/713

redis connection die would causing node crash if none error handle attached.

while I am using the code below to fix this, but shouldn't this belongs to lib itself ?
```
const pubsub = new RedisPubSub({
    connectionListener: (e) => null,
  });
```

**Comment by davidyaha** [comment]
Hmmm that's true I think... I think I still need a way for the library user to override this default behaviour.. Care to PR this?

If you do, please use console.log/error to print out the error.

Thanks ahead!

**Comment by youngboy** [comment]
@davidyaha just onpened pull request, sample output would be like
```
{ Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379 }
```

**Comment by rufaidemir** [comment]
Did you find solition?
