### ISSUE TITLE
Usage without ioredis

### ISSUE THREAD

**Issue by mi-kas** [davidyaha/graphql-redis-subscriptions#221]
Is it possible to use this package also without `ioredis` by providing an own redis client (for example `async-redis`)?

**Comment by jorinvo** [comment]
We are using it with a client from the standard `redis` package. Working fine 🙂

**Comment by davidyaha** [comment]
@mi-kas Yes it is.
Try following the example here https://github.com/davidyaha/graphql-redis-subscriptions#creating-the-redis-client but import your own redis client.

**Comment by mi-kas** [comment]
Thank you both for the clarification
