### ISSUE TITLE
Date objects deserialize to ISO striungs

### ISSUE THREAD

**Issue by axos88** [davidyaha/graphql-redis-subscriptions#226]
Publishing a Date value:
```
  pubSub.publish('foo', { a: new Date() })
```

Will be deserialized to 

```
{ a: "2020-04-16T11:43:00.466Z" }
```

**Comment by axos88** [comment]
This issue is not present on the default, in-memory implementation

**Comment by davidyaha** [comment]
Hey @axos88! Thanks for using this package!
The default deserializer/serializer is basic `JSON.parse()` and `JSON.stringify()`. You can override the behavior by using a [custom reviver](https://github.com/davidyaha/graphql-redis-subscriptions#using-a-custom-reviver) or a [custom serializer/deserializer](https://github.com/davidyaha/graphql-redis-subscriptions/pull/199)
Lmk if that fixes your issue.

**Comment by axos88** [comment]
I added a reviver that checks the format for ISO strings and parses them into Date objects, but this is unexpected behaviour. I would argue it would be a good idea to add a paragraph to the doc stating that a custom reviver is needed for Date objects, which work out-of-the-box with the in-memory implementation

**Comment by davidyaha** [comment]
Sure, would love to merge a PR for that change in the README.
Happy to hear that it worked out though.
