### ISSUE TITLE
Tuning advice

### ISSUE THREAD

**Issue by barendb** [davidyaha/graphql-redis-subscriptions#233]
@davidyaha Was wondering if you have any suggestions/recommendations on how to tune the config settings.

We're seeing some odd behaviour where 100's of connections are generated by only a handful of clients. Being a bit of a Redis noob, I thought I'd ask you first.

Below is a little sample of what we're experiencing
<img width="892" alt="Screen Shot 2020-05-21 at 3 00 51 PM" src="https://user-images.githubusercontent.com/721250/82518913-82ba9900-9b74-11ea-80c2-1df6369a462c.png">

**Comment by davidyaha** [comment]
Hey @barendb! 
Sorry for the late response. Where are you seeing this issue? 
Web -> Server connection or Server -> Redis connection?
If Server -> Redis, what is your config on the Redis client instance?

**Comment by barendb** [comment]
Completely forgot about this, we resolved the issue. Was actually a really stupid mistake on my end. I was opening connections on every context creation 🤦‍♂️ 😂
