### ISSUE TITLE
DateTime Fields only return null in Subscriptions

### ISSUE THREAD

**Issue by GabrielGalatti** [davidyaha/graphql-redis-subscriptions#234]
I was using _graphql-subscriptions_ in my app, but I decided to change to _graphql-redis-subscriptions_, because I can scale the websocket connection with Redis. But the same code that was working is now with a problem. Apparently the DateTime fields always returns null in Subscriptions because  _graphql-redis-subscriptions_ doens't recognize the DateTime type in subscriptions. Does someone have any solution to that?

The error only appears with DateTime fields, and when I log the payload it's all properties there.

`Cannot return null for non-nullable field ProductPayloadSubscription.`

**Comment by GabrielGalatti** [comment]
One solution: Change the type of DateTime field, in subscription, to string.

**Comment by davidyaha** [comment]
Not sure I understand the issue but have you tried this? - https://github.com/davidyaha/graphql-redis-subscriptions#using-a-custom-reviver
