### ISSUE TITLE
Release 2.2.2

### ISSUE THREAD

**Issue by 9at8** [davidyaha/graphql-redis-subscriptions#236]
First of all, thanks for maintaining this project!! :tada: 

One of my projects is blocked due to https://github.com/davidyaha/graphql-redis-subscriptions/commit/0ce0dd4d1a4cf85e3cc7ffbb7c531b09ca91f7fa

Is it possible to release a new version?

cc: @davidyaha

**Comment by davidyaha** [comment]
Done! Sorry about that. Moved to a new machine and forgot to release this patch. You can now get version 2.2.2 on NPM.
