### ISSUE TITLE
Illegal invocation on subscriptions firing 

### ISSUE THREAD

**Issue by minaairsupport** [davidyaha/graphql-redis-subscriptions#265]
I am using sentry for crash reporting and I got this error on subscriptions 

the error on that line 
`      case 0: return [4, this.redisPublisher.publish(trigger, this.serializer ? this.serializer(payload) : JSON.stringify(payload))];
`

here is the full code 
```
 RedisPubSub.prototype.publish = function (trigger, payload) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4, this.redisPublisher.publish(trigger, this.serializer ? this.serializer(payload) : JSON.stringify(payload))];
                    case 1:
                        _a.sent();
                        return [2];
                }
            });
        });
    };

```
error report 

https://sentry.io/share/issue/c40b5be5373f4736bda8af744a3a2207/

screenshot of error 

![Screen Shot 2020-09-29 at 2 45 29 PM](https://user-images.githubusercontent.com/33718103/94560267-af896600-0262-11eb-9ddd-47257c58ef0b.png)

**Comment by davidyaha** [comment]
Hey @minaairsupport, sorry for the late reply. is this still an issue?
if so, please provide a bit more content on your setup. the code you've shared is after babel/ts transpilation so it's a bit harder to figure out what is going on.
Have you passed a custom serializer? is the payload a legal JSON object?

**Comment by minaairsupport** [comment]
I fixed using Using a custom reviver to handle date type and its working so I am going to close this issue
