### ISSUE TITLE
Grammatical Error in README.md 

### ISSUE THREAD

**Issue by mashuDuek** [davidyaha/graphql-redis-subscriptions#327]
Line 114 of `README.md` has a sentence with what appears to be grammatical error. 

> For production usage, it is recommended to send a Redis client from the using code and pass in any options you would like to use. e.g: Connection retry strategy.

I can't tell what was meant to be written here, sorry for that. 
Hope this helps :) and thank you for the module 👍

**Comment by davidyaha** [comment]
@mashuDuek @skabbes Thanks for the comments.
I'll fix the readme with @skabbes suggested text.
