### ISSUE TITLE
All declarations of 'GraphQLFieldExtensions' must have identical type parameters.

### ISSUE THREAD

**Issue by GwamakaCharles** [davidyaha/graphql-redis-subscriptions#374]
an @apollo/query-planner module produces the above error and crashes the project. I've installed graphql-redis-subscription v2.4.0 on a nestJs project.

**Comment by davidyaha** [comment]
Hello @GwamakaCharles, thanks for reaching out!
This only dependency for this package is `iterall` which doesn't have this type I would assume.
It might be that for some reason your install command installed also the peer dependencies?
If it did, that might be the issue. The package is asking for `graphql-subscriptions` as a peer and it might have it's own dependencies that causes the multiple declarations of GraphQLFieldExtensions
Try using `graphql-subscrptions` without `graphql-redis-subscriptions` and then add it in if that works. Those two packages were made to play along so it would probably be a quick change.

I hope this helps.

**Comment by GwamakaCharles** [comment]
This issue is  [SOLVED here](https://github.com/join-monster/join-monster/pull/429). I updated graphql by running **npm install graphql** and everything worked well.
