### ISSUE TITLE
Subscription not working after some time due to browser inactivity even though it seems to be connected

### ISSUE THREAD

**Issue by pkshaky90** [davidyaha/graphql-redis-subscriptions#382]
Subscription stops working after some time due to browser inactivity or some other issue.

**Comment by artyomliou** [comment]
For Apollo Server@^2.0, you can pass a keepAlive setting, for prevent connection being killed by proxy:
`
const server = new ApolloServer({
  subscriptions: {
    keepAlive: 20 * 1000 // 20 seconds
  }
});
`

**Comment by davidyaha** [comment]
I don't think this is strictily a graphql-redis-subscriptions issue. The WS connection is being handled by apollo server and client.
Happy to re-open if that issue persists.
