### ISSUE TITLE
Need Some help.

### ISSUE THREAD

**Issue by HammadUllahKhan12** [davidyaha/graphql-redis-subscriptions#397]
Whenever I call the subscription in the dev environment (local host). It gives subscription undefined but it working fine on production. Need some help.

![image](https://user-images.githubusercontent.com/48718737/123986513-cd494e80-d9df-11eb-8192-4d7d54964082.png)

**Comment by davidyaha** [comment]
Hey @HammadUllahKhan12 , is this still an issue?

**Comment by HammadUllahKhan12** [comment]
hey, @davidyaha Yes the issue is fixed.
