### ISSUE TITLE
Can you please update ioredis dependency in package.json?

### ISSUE THREAD

**Issue by Gilwe** [davidyaha/graphql-redis-subscriptions#460]
https://app.snyk.io/vuln/SNYK-JS-IOREDIS-1567196

Can you please update ioredis to at least 4.28?

**Comment by dhenson02** [comment]
:+1:

PR #455 appears to be ready to facilitate (auto gen PR)

**Comment by Gilwe** [comment]
@dhenson02 any change you might know when is it going to merge and be released?

**Comment by davidyaha** [comment]
Sure. Available at v2.4.2

**Comment by Gilwe** [comment]
@davidyaha `ioredis` in the package.json is still using the old version of `ioredis` in the dev/optional/regular dependencies :(

**Comment by davidyaha** [comment]
That's using `^4.17.3` which is any minor version above 4.17.3 isn't it?
the lock file was updated so dev dependencies are covered.
You can definitely use any version available above 4.17.3 without an issue as the `ioredis` is defined only as optional dependency.

Do you see any caveat there?

**Comment by Gilwe** [comment]
oh man I totally missed the Exponent symbol.
thanks a lot!
