### ISSUE TITLE
Geoadd, set and georadius question

### ISSUE THREAD

**Issue by mikegallina** [davidyaha/graphql-redis-subscriptions#51]
Hi all, great work. Somewhat newbie disclosure, Im new to graphql and new to redis subscriptions but have fair amount of experience with redis in general. I'm trying to determine/conceptualize how and if I can utilize graphql-redis-subscriptions to 

A. perform geo-add
B. change(re"set") the value of hash 
C. perform a georadius query

Currently doing above this via a simple service but would like to experiment the same implementation via graphql-redis-subscriptions, is it feasible? Would graphql add complexity or any lag to response if feasible? 

thanks! Great work!

**Comment by davidyaha** [comment]
Hey @mikegallina,
Thanks for taking interest in this package!

I personally haven't tried redis's geo functions but a quick search led me to think it might be possible to publish geo-add events. 
It seems that the geo commands was based on an implementation written by @mattsta. In his post about it, he mentions that every geoadd will publish on a geo channel, take a look [here](https://matt.sh/redis-geo#_bonus-real-time-streaming-location-updates)

It seems to me that you sure can subscribe to those channel using graphql and do geoadd on a `updateLocation` mutation. This will then publish on the channel you are subscribed on and will pass the event through the GraphQL execute function. 

From what I've seen, GraphQL has a definite hit on performance if you are running a huge selection set in your subscription but it seems to me that it's greater flexibility on how events look will be worth it.

I would love to hear how that works out for you, so please keep me posted!

**Comment by davidyaha** [comment]
Stale issue. If this interests someone, please comment about it.
