### ISSUE TITLE
TypeError: pub_sub_1.pubSub.asyncIterator is not a function

### ISSUE THREAD

**Issue by akaNightmare** [davidyaha/graphql-redis-subscriptions#61]
Hi, 
[graphql-subscriptions](https://github.com/apollographql/graphql-subscriptions/blob/master/CHANGELOG.md#040) has been released with version `0.4.0`, and graphql-redis-subscriptions does not work, because breaking changes.

**Comment by ArnaudRinquin** [comment]
This compatibility issue is quite a problem for us, preventing from using the latest version of graphql subscriptions implementations. @davidyaha, is there anything we can do to help? [This comment](https://github.com/apollographql/graphql-subscriptions/issues/70#issuecomment-306421334) on a related issue seems useful.

**Comment by akaNightmare** [comment]
@ArnaudRinquin It's not quite ok, because all libs which extend main interface of graphql-subscriptions should implement all public methods (in this case `asynciterator` etc.).

**Comment by ArnaudRinquin** [comment]
I know it's not ok! I guess everybody here is waiting for @davidyaha to save us all from this situation but he does not seem to be working on the issue. I'm trying to be helpful by providing a bit of guidance / hints. It's all.

I'll try to work on it in the coming days unless salvation comes from anyone of us.

**Comment by akaNightmare** [comment]
@ArnaudRinquin thanks for your help, I can create a some PR, but it would be good to merge it in this repository

**Comment by davidyaha** [comment]
Hey @akaNightmare @ArnaudRinquin,
Sorry to keep you waiting but I will be able to work on the API only next week.
I'll happily review and merge any of your PR's so if you know what to do, go for it!

Thanks for using this project and I hope there is no resentment :)

**Comment by AlexLeung** [comment]
How does this look so far? https://github.com/AlexLeung/graphql-redis-subscriptions/blob/master/src/redis-async-iterator.ts
I'm still working on writing the tests.

**Comment by davidyaha** [comment]
Thanks @AlexLeung! 

So far looks great!
There seem to be no specific implementation to the RedisPubSub, do you think you can create a function that will take a PubSubEngine interface and return a AsyncIterator?

This kind of implementation, could be merged into graphql-subscriptions potentially to support all older PubSubEngine implementations like this:
https://github.com/davidyaha/graphql-mqtt-subscriptions
or this
https://github.com/cdmbase/graphql-rabbitmq-subscriptions

What are your thoughts about it?
Also, please open a PR so I or any other apollo member could review, later on you can add tests before we merge.

Thanks again!

**Comment by AlexLeung** [comment]
That's a good point! This implementation is basically already generic so it should be able to apply to any PubSubEngine. I'm dealing with a few bugs, and the tests are written now. Once I fix all that I'll push and submit a PR.

**Comment by davidyaha** [comment]
Awesome!

**Comment by davidyaha** [comment]
So I've talked with @dotansimha offline and it seems like graphql-subscriptions will soon become a util package to allow for features like filter and transform hooked composed on top of any AsyncIterator that will be returned from a subscribe resolver.
This means that this and other PubSubEngine instances should probably be looked at as connectors.

If for `query` and `mutate` we use static db connectors,  for `subscribe` we will use pubSub engines connectors.
The way those connectors were supplied until now to the resolvers is using the context. (at least in the apollo ecosystem)

I think this means that we should do the same for redis/mqtt/rabbitMq connectors.
This way, your server will only have one (or two for redis) connections open and the `AsyncIterator` util @AlexLeung is working on will then be used to transform a `PubSubEngine` into `AsyncIterator`.

So @AlexLeung if you can, please go for some util with a signature like so:
`(pubsub: PubSubEngine) => AsyncIterator<Event>`

Your code already looks like it's on the right direction, probably just some naming changes is needed.

Thanks for the contribution!

**Comment by AlexLeung** [comment]
Shouldn't the signature also take in a `string | string[]` for the events to watch?

**Comment by davidyaha** [comment]
correct :)

**Comment by AlexLeung** [comment]
Ready for review. I know that the best solution will be to push this to `graphql-subscriptions` directly since the implementation is generic, but for now, I'd really appreciate it if we could publish this change to the `gaphql-redis-subscriptions` package for the time being.

**Comment by AlexLeung** [comment]
Until this resolves, feel free to use [graphl-redis-subscriptions-async-iterator](https://www.npmjs.com/package/graphql-redis-subscriptions-async-iterator)

**Comment by davidyaha** [comment]
Closed with #65

**Comment by davidyaha** [comment]
Released as [v1.2.0](https://www.npmjs.com/package/graphql-redis-subscriptions)
