### ISSUE TITLE
Update documentation for Trigger Transform

### ISSUE THREAD

**Issue by marklawlor** [davidyaha/graphql-redis-subscriptions#67]
Trigger Transform relies on the Subscription Manager constructor [which is now deprecated](https://github.com/apollographql/graphql-subscriptions#subscriptionmanager-deprecated).

Is it still possible to do filtering based upon the redis subscription?

**Comment by davidyaha** [comment]
@AlexLeung Care to chime in?

@marklawlor Would really appreciate a PR for updating the README file!

**Comment by AlexLeung** [comment]
I believe the TriggerTransform is a method passed into the RedisPubSub constructor so it still should be working with the current implementation of asyncIterator, since the PubSubAsyncIterator just makes calls to the subscribe method directly. I haven't tested for this though so someone will have to confirm.

**Comment by marklawlor** [comment]
Looking at the code for triggerOptions, it does appear to just pass straight through, but now I'm unsure how the channelOptions parameter should be passed.

Previously using a subscriptionManager the client could send up a variable `repoName` which would be transformed by the trigger transform to a more specific redis subscriptionvia the channelOptions parameter

```
const subscriptionManager = new SubscriptionManager({
  schema,
  setupFunctions: {
    commentsAdded: (options, {repoName}) => ({
      'comments.added': {
        channelOptions: {path: [repoName]},
      },
    }),
  },
  pubsub,
});
```

Looking at the new syntax, I'm unsure how a client can pass a variable to the `pubsub.asyncIterator`

```
export const resolvers = {
  Subscription: {
    somethingChanged: {
      subscribe: withFilter(() => pubsub.asyncIterator(SOMETHING_CHANGED_TOPIC), (payload, variables) => {
        return payload.somethingChanged.id === variables.relevantId;
      }),
    },
  },
}
```

**Comment by davidyaha** [comment]
@marklawlor ATM it seems like using both `withFilter` and TriggerTransform like functionality is not easily possible due to `withFilter` not passing arguments to the asyncIterator provider function.
Take a look  here: https://github.com/apollographql/graphql-subscriptions/blob/master/src/with-filter.ts#L6-L7

It seems like a fairly simple fix so I think that PR `graphql-subscriptions` with that should be a thing if you don't mind opening it.

In the meantime, you can just provide your own `subscribe` function in this manner:
```javascript
const filtered = (asyncIterator, filter) => withFilter(
  () => asyncIterator, 
  filter,
);

export const resolvers = {
  Subscription: {
    somethingChanged: {
      subscribe: (_, args, context, info) => filtered(
        pubsub.asyncIterator(`${SOMETHING_CHANGED_TOPIC}.${args.relevantId}`),
        (payload, variables) => payload.somethingChanged.id === variables.relevantId,
      ),
    },
  },
}
```

**Comment by farzd** [comment]
Hey Sorry to jump on this as i know you probably havent had time to update the doc's but having similar difficulty implementing this without the subscription manager,

anytime i subscribe using the redis pubsub, i get this
``
[{"message":"Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory."}]
``

``
    new SubscriptionServer({
        execute,
        subscribe,
        schema
    }, {
        server,
        path: '/subscriptions',
    });
``

works fine if i use the pubsub from graphql-subscriptions

**Comment by davidyaha** [comment]
Hey @farzd! Please open a new issue on this and if you can, provide more information on your setup.
I'll try to help as much as I can.

**Comment by patte** [comment]
dear @davidyaha I tested your workaround, but couldn't make it work. 

this works:
``` 
const { PubSub } = require('graphql-subscriptions')
const { withFilter  } = require('graphql-subscriptions')
pubsub = new PubSub()

module.exports = {
  subscribe: withFilter(() => pubsub.asyncIterator('ASDF'), (payload, variables) => true)
}

```

this does not:
```
const filtered = (asyncIterator, filter) => withFilter(
  () => asyncIterator,
  filter,
);
module.exports = {
  subscribe: (_, args, context, info) => filtered(pubsub.asyncIterator('ASDF'), (payload, variables) => true)
```

when I try to subscribe (from graphiql) I get the following error message: `Subscription must return Async Iterable. Received: function (rootValue, args, context, info) {↵        var asyncIterator = asyncIteratorFn();↵        var getNextPromise = function () {↵            return asyncIterator↵                .next() ...`

any ideas?

**Comment by davidyaha** [comment]
@patte Ah yeah missed it!
So actually you should probably pass the arguments to the returned function:
```javascript
module.exports = {
  subscribe: (_, args, context, info) => filtered(pubsub.asyncIterator('ASDF'), (payload, variables) => true)(_, args, context, info)
}
```

Take a look over here https://github.com/apollographql/graphql-subscriptions/blob/master/src/with-filter.ts#L6-L7
You'll see how those args are being used.

Hope it helps!

**Comment by tgdn** [comment]
Your docs still make use of  `SubscriptionManager`, is there a workaround which isn't a hack?

**Comment by davidyaha** [comment]
Fixed with https://github.com/davidyaha/graphql-redis-subscriptions/commit/dd70b23d6f8da2841a0e807a25a1d1bddbbad5ab
