### ISSUE TITLE
subscriptionMap seems to be leaking memory

### ISSUE THREAD

**Issue by rricard** [davidyaha/graphql-redis-subscriptions#7]
Hello,

Since we implemented subscriptions in our app (including this package) we see sometimes elevated memory usage over time. I'm not quite sure what's happening in there but I see a lot of the RedisPubSub's subscriptionMap retaining some memory:

<img width="1394" alt="developer_tools_-_https___trace_risingstack_com_app_" src="https://cloud.githubusercontent.com/assets/246520/19381366/8ac1febc-91fb-11e6-84d9-1f0a97287778.png">

This may be due to many different things: first of all, we have a kue job queue hooked in the same pubsub. That would explain a good chunk of the retained memory ("Matrix" part in the retained objects).

However, from what I gather in your source, there is no cleaning in the subscriptionMap of the Array mapped by your subscriptionId: https://github.com/davidyaha/graphql-redis-subscriptions/blob/master/src/redis-pubsub.ts#L63:L83

I'll try to things to mitigate the issue:

- separate redis pubsubs: this may already reduce the retained memory but may not stop the leak
- a PR here to clearly delete in the subscriptionMap on unsubscription

Maybe we should consider mapping the subscriptions using a WeakMap, avoiding maintaining the cleaning of the retained objects in the subscription map...

**Comment by rricard** [comment]
@davidyaha we may want to reopen that while I assess if it's there!

**Comment by davidyaha** [comment]
Yep sorry. Auto closed...

**Comment by rricard** [comment]
Figured out, that was my bad actually!

**Comment by rricard** [comment]
Awesome! Thanks for the version bump!

**Comment by rricard** [comment]
Well, I'm confused, I still see retained objects for no reason:

<img width="1394" alt="developer_tools_-_https___trace_risingstack_com_app_" src="https://cloud.githubusercontent.com/assets/246520/19386229/52148446-9213-11e6-992f-b5034cc7fa48.png">

(that's after the patch)

**Comment by rricard** [comment]
I have to check if my deploy worked though...

**Comment by rricard** [comment]
Crossed-checked with local deployment: same issue ... Will need to dive in the code again.

<img width="1396" alt="chrome-devtools___devtools_remote_serve_file__60cd6e859b9f557d2312f5bf532f6aec5f284980_inspector_html_experiments_true_v8only_true_ws_localhost_9229_node" src="https://cloud.githubusercontent.com/assets/246520/19386484/bff7f910-9214-11e6-8b26-cfb2b73931a4.png">

@davidyaha are we sure unsubscribe events are correctly fired ? In that case it may be worth to open an issue in graphql-subscriptions

**Comment by rricard** [comment]
I'll cross-check with the non-redis, event-emitter based pubsub to see if there is the same issue with it.

**Comment by rricard** [comment]
@davidyaha: I just figured out what's wrong! You may have forgot to run `tsc` before publishing ... I don't see the change in my compiled JS ...

**Comment by davidyaha** [comment]
Whoops!! Sorry for your wasted time. I usually run tests before publishing so it does that for me. Couple of minutes and I'll release a new version

**Comment by rricard** [comment]
I made a PR ensuring that kind of stuff doesn't happen again ;)

**Comment by davidyaha** [comment]
LMK if this is still the case!

**Comment by rricard** [comment]
I think it's good now!
