### ISSUE TITLE
Guaranteed delivery?

### ISSUE THREAD

**Issue by scf4** [davidyaha/graphql-redis-subscriptions#76]
In [this article](https://dev-blog.apollodata.com/new-release-of-graphql-subscriptions-for-javascript-f11be19e6569) it mentions delivery guarantees:

> We worked with David Yahalomi to create the graphql-redis-subscriptions and graphql-mqtt-subscriptions packages, which can be easily dropped in as a replacement for the default PubSub object without making any changes to the rest of your code. 

>Using an external pub/sub system gives you more publication features — such as persistence, caching, **delivery guarantees** and other optimizations.

Does `graphql-redis-subscriptions` support guaranteed delivery, and how would one go about implementing it?

**Comment by davidyaha** [comment]
Hey @scf4!
Thanks for the interest in this package.
Redis as a pubsub broker does not provide any built in delivery guarantee mechanism out of the box.
It is possible to implement one on top of it but at times when delivery guarantee is needed, I would advise using the graphql-mqtt-subscriptions package instead (or in conjunction?)
MQTT supports QoS parameter which by using level 1 requires any mqtt client to give you publish acknowledge message as response.
If you want to learn more I would advise going here http://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels

After making sure that you services does not loose messages, you can go over and either create an event tracking mechanism to make sure all clients have received their messages or you can create a client side MQTT transport for apollo and send the events (after graphql evaluate call) directly using QoS of at least 1.

Hope that gives some good direction to follow.

**Comment by davidyaha** [comment]
@scf4 Is it safe to close this one?

**Comment by scf4** [comment]
@davidyaha yes, sorry for the late response and thank you for the great reply!
