### ISSUE TITLE
Is it possible to use ElasticCache (Redis) instead of self hosted Redis

### ISSUE THREAD

**Issue by gouravd** [davidyaha/graphql-redis-subscriptions#85]
Not sure how to set the connection parameters

**Comment by davidyaha** [comment]
@gouravd With version 1.3.0 You can now pass in a `ioredis` connection object so support for everything ioredis supports is possible. Please refer to #78 and [ioredis docs](https://github.com/luin/ioredis) for more info.
Would love a PR for the readme if you got this one working!

Thanks for your interest!

**Comment by gouravd** [comment]
@wyattjoh Thanks, I did try but it wasn't connecting...probably something silly on my side..will recheck.

@davidyaha sure, let me try this and will get back..if things work as expected, will proceed with the readme PR

**Comment by davidyaha** [comment]
@gouravd  Any news here?

**Comment by wtfleming** [comment]
We are using a ElasticCache hosted redis and used the instructions from this repo's readme for the connection params.
