### ISSUE TITLE
asynciterator test fails when run independently

### ISSUE THREAD

**Issue by veeramarni** [davidyaha/graphql-redis-subscriptions#90]
I tried testing the async iterator test case independently and it fails. Try  to run this test. 
**https://github.com/veeramarni/graphql-redis-subscriptions/blob/master/src/test/integration-tests.ts**

**Comment by davidyaha** [comment]
Hey @veeramarni!

Thanks for taking a look here!


Just to clarify as this test is in the current test suite that's passing.
If you run the whole test suite that works?
Could you maybe try uncommenting the code back and just use it.only in order to run the one test?

**Comment by veeramarni** [comment]
Yes, basically with all tests it running fine. But the tests that I have pointed were failing. It could be just the test case that was having the issue.

**Comment by davidyaha** [comment]
Hmm 🤔 
Okay thanks for reporting this issue.
I'll try out when I have a bit more time for maintenance.

Do you see the issue when actually using asynciterator methods?

**Comment by j3ddesign** [comment]
I've noticed issues with the integration tests myself when working on https://github.com/davidyaha/graphql-redis-subscriptions/pull/108 locally.

When running `npm test` the Integration tests simply return the following
```
1) PubSubAsyncIterator should allow subscriptions:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

I noticed when submitting the PR that jenkins successfully ran those integration tests so wanted to give a bit more information on my environment in case that's relevant.
Node version: 8.9.1
Windows 10
Installation steps before running tests:
 - git clone
 - npm install
 - npm test

**Comment by jonas-arkulpa** [comment]
Possible cause:
`const iterator = pubSub.asyncIterator(eventName);`
The subscription takes some time. Even if the promises resolve immediately it waits for the next tick.
If the publish happens right after the call to asyncIterator the global listener is still undefined.
`const publishSpy = spy((channel, message) => listener && listener(channel, message));`
If all tests are running the reused global listener might already be set.

`setTimeout(() => pubSub.publish(eventName, { test: true }), 0)`
Should fix the tests but I'm not sure if that is the most elegant solution.
